### ISSUE TITLE
Bridge Troll loads indefinitely

### ISSUE THREAD

**Issue by irrationalRock** [humphd/bridge-troll#2]
Currently Bridge Troll is loading indefinitely for me. 
Bridge Troll was working for me a couple of days ago but when I got the latest changes today it doesn't load the map and is stuck on the loading screen.

Example:
![bug](https://user-images.githubusercontent.com/16523071/37379616-b612a4a4-270a-11e8-8c34-e838f6649160.gif)

Steps to reproduce:
1. run `npm start` on Git Bash

Expected Result:
To load the map

Node version: 8.9.4
OS: Windows 10

**Comment by humphd** [comment]
This is mostly likely a permission issue for geolocation in your browser.  The site needs access to it to be able to start (we should probably add some kind of UI for error cases where we can't get it).

Try something for me:

* Update to my latest code on `master`.  Add my repo as a remote named `upstream`, and `git pull upstream master`
* run `npm run debug` instead of `npm start`.  This will use a fake geolocation implemenation I wrote vs. the one in the browser
* Open the page like this `http://localhost:1234/?loglevel=info` and open your browser console to see what it says

Let me know what you find.

**Comment by irrationalRock** [comment]
So I get this error message when running npm run debug:

```$ npm run debug

> bridge-troll@1.0.0 debug E:\release2\bridge-troll
> FAKE_GEO=1 parcel src/index.html

'FAKE_GEO' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bridge-troll@1.0.0 debug: `FAKE_GEO=1 parcel src/index.html`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bridge-troll@1.0.0 debug script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mquan\AppData\Roaming\npm-cache\_logs\2018-03-14T02_34_05_921Z-debug.log
```

**Comment by humphd** [comment]
Fixed in https://github.com/humphd/bridge-troll/commit/26b1af65fc14f2ce2544d0196f1ddf55fa3140bd.  Thanks for filing this, I hadn't tested on Windows.

Anyone else hitting this, pull my latest `master` and then `npm install`.  Should work then.
